import jsPDF from 'jspdf';
import { getCompanyInfo } from '../config/invoiceSettings';
import type { Database } from '../lib/database.types';

type Purchase = Database['public']['Tables']['purchases']['Row'];
type PurchaseItem = Database['public']['Tables']['purchase_items']['Row'];
type Farmer = Database['public']['Tables']['farmers']['Row'];
type Product = Database['public']['Tables']['products']['Row'];
type CropSale = Database['public']['Tables']['crop_sales']['Row'];

interface PurchaseWithDetails extends Purchase {
  farmers?: Farmer;
  purchase_items?: (PurchaseItem & { products?: Product })[];
}

interface SaleWithFarmer extends CropSale {
  farmers?: Farmer;
}

class SimpleInvoiceGenerator {
  private doc: jsPDF;
  
  constructor() {
    this.doc = new jsPDF();
  }

  generatePurchaseInvoice(purchaseData: PurchaseWithDetails) {
    try {
      this.doc = new jsPDF();
      const companyInfo = getCompanyInfo();
      
      // Header
      this.doc.setFontSize(20);
      this.doc.setTextColor(33, 150, 243);
      this.doc.text(companyInfo.name, 105, 20, { align: 'center' });
      
      // Invoice title
      this.doc.setFontSize(16);
      this.doc.setTextColor(0, 0, 0);
      this.doc.text('PURCHASE INVOICE', 105, 40, { align: 'center' });
      
      // Invoice details
      this.doc.setFontSize(12);
      let yPos = 60;
      
      this.doc.text(`Invoice #: PUR-${String(purchaseData.id).padStart(6, '0')}`, 20, yPos);
      yPos += 8;
      
      const dateStr = purchaseData.date ? new Date(purchaseData.date).toLocaleDateString() : 'N/A';
      this.doc.text(`Date: ${dateStr}`, 20, yPos);
      yPos += 8;
      
      this.doc.text(`Payment Type: ${purchaseData.payment_type || 'N/A'}`, 20, yPos);
      yPos += 15;
      
      // Farmer details
      this.doc.setFontSize(14);
      this.doc.text('Farmer Details:', 20, yPos);
      yPos += 10;
      
      this.doc.setFontSize(11);
      this.doc.text(`Name: ${purchaseData.farmers?.name || 'Unknown'}`, 20, yPos);
      yPos += 6;
      
      this.doc.text(`Phone: ${purchaseData.farmers?.phone_number || 'N/A'}`, 20, yPos);
      yPos += 6;
      
      this.doc.text(`Address: ${purchaseData.farmers?.address || 'N/A'}`, 20, yPos);
      yPos += 15;
      
      // Items header
      this.doc.setFontSize(12);
      this.doc.text('Items:', 20, yPos);
      yPos += 10;
      
      // Items list
      if (purchaseData.purchase_items && purchaseData.purchase_items.length > 0) {
        purchaseData.purchase_items.forEach((item, index) => {
          const productName = item.products?.name || 'Unknown Product';
          const quantity = Number(item.quantity || 0).toFixed(2);
          const rate = Number(item.rate || 0).toFixed(2);
          const total = (Number(item.quantity || 0) * Number(item.rate || 0)).toFixed(2);
          
          this.doc.text(`${index + 1}. ${productName}`, 25, yPos);
          this.doc.text(`Qty: ${quantity} | Rate: Rs.${rate} | Total: Rs.${total}`, 30, yPos + 5);
          yPos += 15;
        });
      }
      
      // Total
      yPos += 10;
      this.doc.setFontSize(14);
      const totalAmount = Number(purchaseData.total_amount || 0);
      this.doc.text(`TOTAL AMOUNT: Rs. ${totalAmount.toLocaleString()}`, 20, yPos);
      
      // Footer
      yPos = 260; // Fixed position near bottom
      this.doc.setFontSize(9);
      this.doc.setTextColor(100, 100, 100);
      this.doc.text('Generated by Artiya Management System', 20, yPos);
      this.doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, yPos + 5);
      
      // Download
      this.doc.save(`Purchase_Invoice_${purchaseData.id}_${new Date().toISOString().split('T')[0]}.pdf`);
      
    } catch (error) {
      console.error('Error generating purchase invoice:', error);
      throw error;
    }
  }

  generateSaleInvoice(saleData: SaleWithFarmer) {
    try {
      this.doc = new jsPDF();
      const companyInfo = getCompanyInfo();
      
      // Header
      this.doc.setFontSize(20);
      this.doc.setTextColor(33, 150, 243);
      this.doc.text(companyInfo.name, 105, 20, { align: 'center' });
      
      // Invoice title
      this.doc.setFontSize(16);
      this.doc.setTextColor(0, 0, 0);
      this.doc.text('CROP SALE INVOICE', 105, 40, { align: 'center' });
      
      // Invoice details
      this.doc.setFontSize(12);
      let yPos = 60;
      
      this.doc.text(`Invoice #: SALE-${String(saleData.id).padStart(6, '0')}`, 20, yPos);
      yPos += 8;
      
      const dateStr = saleData.date ? new Date(saleData.date).toLocaleDateString() : 'N/A';
      this.doc.text(`Date: ${dateStr}`, 20, yPos);
      yPos += 8;
      
      this.doc.text(`Sold To: ${saleData.sold_to || 'N/A'}`, 20, yPos);
      yPos += 15;
      
      // Farmer details
      this.doc.setFontSize(14);
      this.doc.text('Farmer Details:', 20, yPos);
      yPos += 10;
      
      this.doc.setFontSize(11);
      this.doc.text(`Name: ${saleData.farmers?.name || 'Unknown'}`, 20, yPos);
      yPos += 6;
      
      this.doc.text(`Phone: ${saleData.farmers?.phone_number || 'N/A'}`, 20, yPos);
      yPos += 15;
      
      // Sale summary
      this.doc.setFontSize(14);
      this.doc.text('Sale Summary:', 20, yPos);
      yPos += 10;
      
      this.doc.setFontSize(12);
      const totalValue = Number(saleData.total_value || 0);
      const commissionPercent = Number(saleData.commission_percent || 0);
      const commissionAmount = (totalValue * commissionPercent) / 100;
      const netPayable = totalValue - commissionAmount;
      
      this.doc.text(`Total Sale Value: Rs. ${totalValue.toLocaleString()}`, 20, yPos);
      yPos += 8;
      
      this.doc.text(`Commission (${commissionPercent}%): Rs. ${commissionAmount.toLocaleString()}`, 20, yPos);
      yPos += 8;
      
      this.doc.setTextColor(76, 175, 80);
      this.doc.text(`Net Payable: Rs. ${netPayable.toLocaleString()}`, 20, yPos);
      this.doc.setTextColor(0, 0, 0);
      
      // Footer
      yPos = 260; // Fixed position near bottom
      this.doc.setFontSize(9);
      this.doc.setTextColor(100, 100, 100);
      this.doc.text('Generated by Artiya Management System', 20, yPos);
      this.doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, yPos + 5);
      
      // Download
      this.doc.save(`Sale_Invoice_${saleData.id}_${new Date().toISOString().split('T')[0]}.pdf`);
      
    } catch (error) {
      console.error('Error generating sale invoice:', error);
      throw error;
    }
  }
}

// Export singleton instance
export const simpleInvoiceGenerator = new SimpleInvoiceGenerator();
